### ISSUE TITLE
little doubt

### ISSUE THREAD

**Issue by f2014169** [udaykrishna/unCap#1]
in the login.py file what does creds['mode']=191 do?

**Comment by udaykrishna** [comment]
~~~ python
creds['mode']=191 # lets Cyberoam know that user is sending a login request
creds['mode']=193 # similarly this implies that the request is a logout request
~~~

**Interesting thing about logout is that a request with `cred['mode']=193` will log you out even without sending a username, unCap sends username just because web portal does and i didn't want to break things on the server side**
